### ISSUE TITLE
Standard Error of the Global Fit

### ISSUE THREAD

**Issue by MalteWell** [erdzeichen/KiMoPack#14]
Hi,
I am looking for an option to give me the symmetric standard error of the applied fit in terms of a Gaussian distribution instead of the unsymmetric lower and upper limit of the F-distribution. I was thinking that, for example, knowing the degrees of freedom of the numerator and the degrees of freedom of the denominator, it should not be an issue to calculate the standard error. Could you help me with that?
Thank you!

**Comment by erdzeichen** [comment]
Hej Malte,
in principle the full fit output is returned in the "re" object so if your object is called "ta" then "ta.re[''fit_output'']". There you can find the usual co-valence matrix. However for Nelder meat optimizer that does not make much sense. 
The challenge is that one needs to re-optimise all other parameters for each step and then actually one has to look for when is the one parameter one is currently changing above a threshold. 
As the local hyper-plane (the plane that is formed from the other parameter) can have any shape this form is usually not symmetric. So in short when looking for the threshold when the error is larger than statistical defined, you will not be able to find a "symmetric" error because of the shape of the hyper plane at this place. 

I think the closest to your request is indeed the error from the fit during which you do not re-optimise the other parameter, then you might find a standard error. Anyhow I added a new feature for you (6.13.8) . if you use a parameter par['error_param_fix'] together with confidence interval. Then the program will freeze the other parameter during the optimization.

Finally you can do what you would like to do manually.  After the fit:

"par=ta.par_fit_output" write your results to the input

output=[]
for a in np.arange(1,3,0.1):
  par['my_key'].value=a
  for key in par.keys(): # this is changing all parameter vary to false = you can run the Global fit without changing anything
      par[key].vary=False
  ta.par=par
  ta.Fit_Global() #this gives you the error
  output['%g'%a]=ta.re['error']

Then you have to define where you want to cut off. The function pf.s2_vs_smin2 calculates the f-values I use
hope that helps
Jens
